name: Build and test
on:
  pull_request:
    branches:
      - master

jobs:
  build-test:
    name: Build and test
    uses: HavenDV/workflows/.github/workflows/dotnet_build-test-publish.yml@main
    with:
      os: windows-latest
      generate-build-number: false
      conventional-commits-publish-conditions: false
      enable-caching: false
      additional-test-arguments: '--logger GitHubActions'